server:
  port: 7070

spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;DatabaseName=LAS
    username: sojourner
    password: sojourner
    tomcat:
      validation-query: SELECT 1
      test-on-borrow: true
      test-while-idle: true
  jpa:
    database-platform: SQLServer
    show-sql: true
  main:
      sources: za.co.yellowfire.pathfinder.PathfinderApplication

logging:
  level:
    org.springframework: INFO
    org.hibernate: INFO


